{
    types: {
        "Contributor" : {
            pluralLabel: "Contributors",
        "Team Meeting" : {
            pluralLabel: "Team Meetings",
        "Dev Meeting" : {
            pluralLabel: "Dev Meetings",
        "Design Meeting" : {
            pluralLabel: "Design Meetings",
        "Test Event" : {
            pluralLabel: "Test Events",
        "Event" : {
            pluralLabel: "Events"
        }
        }
        }
        }
        }
        }
    },
    properties: {
        "co-winner" : {
            valueType: "item"
        }
    },
    "items" : [
        {   type :                  "Contributor",
            label :                 "Michael Riordan",
            discipline :            "Open Publishing Lab",
            "last-name" :           "Riordan",
            date :                  "2008-01",
            relationship :          "Director",
            "relationship-detail" : "Mentor and Product Owner",
            url :                   "http://opl.rit.edu",
            imageURL :              "http://nobelprize.org/nobel_prizes/economics/laureates/2001/akerlof_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "David Pankoff",
            discipline :            "RIT Library",
            shared :                "yes",
            "last-name" :           "Pankoff",
            date :                  "2008-01",
            relationship :          "Advisor",
            "relationship-detail" : "Curator, Cary Library",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1976/richter_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Matthew Bernius",
            discipline :            "Open Publishing Lab",
            shared :                "yes",
            "last-name" :           "Bernius",
            date :                  "2008-02",
            relationship :          "Mentor",
            "relationship-detail" : "Developer and Future Mentor",
            url :                   "http://opl.rit.edu",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1956/shockley_thumb.jpg",
        },
        {   type :                  "Contributor",
            label :                 "John Karahalis",
            discipline :            "Open Publishing Lab",
            shared :                "yes",
            "last-name" :           "Karahalis",
            date :                  "2008-02",
            relationship :          "Drupal Developer",
            "relationship-detail" : "Theming, Modules, Site",
            url :                   "http://opl.rit.edu",
            imageURL :              "http://nobelprize.org/nobel_prizes/physics/laureates/1998/tsui_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Mark Newell",
            discipline :            "Open Publishing Lab",
            shared :                "no",
            "last-name" :           "Newell",
            date :                  "2008-03",
            relationship :          "Drupal Developer",
            "relationship-detail" : "Theming and Development, Co-op with Rochester Democrat & Chronicle",
            url :                   "http://opl.rit.edu",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Remy DeCausemaker",
            discipline :            "FOSS@RIT",
            "last-name" :           "DeCausemaker",
            date :                  "2010-06",
            relationship :          "Hacktivist & Storyteller",
            "relationship-detail" : "Facilitation of Meetings and Development. Touchstone for each discipline, for each team",
            url :                   "http://foss.rit.edu/blog/decause",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Stephen Jacobs",
            discipline :            "FOSS@RIT",
            "last-name" :           "Jacobs",
            date :                  "2010-06",
            relationship :          "Mentor",
            "relationship-detail" : "Faculty Advisor of FOSS@RIT, Professor of Interactive Games & Media",
            url :                   "http://igm.rit.edu/",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Vic Perotti",
            discipline :            "Digital Entrepreneurship",
            "last-name" :           "Perotti",
            date :                  "2010-06",
            relationship :          "Mentor",
            "relationship-detail" : "Professor RIT College of Business, Champion of Digital Business",
            url :                   "http://cob.rit.edu/",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Andrea Hickerson",
            discipline :            "Journalism",
            "last-name" :           "Hickerson",
            date :                  "2010-06",
            relationship :          "Mentor",
            "relationship-detail" : "Professor RIT Department of Communication",
            url :                   "http://www.rit.edu/cla/communication/journalism.php",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Jaclyn Donner",
            discipline :            "Graphic Design",
            "last-name" :           "Donner",
            date :                  "2010-11",
            relationship :          "Designer",
            "relationship-detail" : "Jackie Designed everything from our Logos, to our icons and T-Shirts. She is a rockstar",
            url :                   "http://jackiedonner.tumblr.com",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Mark DeMayo",
            discipline :            "FOSS@RIT",
            "last-name" :           "DeMayo",
            date :                  "2010-11",
            relationship :          "Developer & Designer",
            "relationship-detail" : "As one of our few front-end developers with Drupal experience, Mark was really the lynchpin between the design and dev team.",
            url :                   "http://people.rit.edu/~mxd6823",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Ariel Zamparini",
            discipline :            "FOSS@RIT",
            "last-name" :           "Zamparini",
            date :                  "2010-11",
            relationship :          "Drupal Developer",
            "relationship-detail" : "Working primarily in the back-end and module research, Ariel provided his Drupal expertise when he could",
            url :                   "http://arielzamparini.com",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Ben Vanderberg",
            discipline :            "Open Publishing Lab",
            "last-name" :           "Vanderberg",
            date :                  "2011-03",
            relationship :          "Designer",
            "relationship-detail" : "Ben's firm grasp of UI, web design, and Graffle was a boon to the Design team. He really shined as a Project Leader.",
            url :                   "http://www.benvanderberg.com/about",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Dustin Wright",
            discipline :            "Open Publishing Lab",
            "last-name" :           "Wright",
            date :                  "2011-03",
            relationship :          "Designer",
            "relationship-detail" : "Dustin coordinated typography with Jackie, and produced many a mockup",
            url :                   "http://www.linkedin.com/pub/dustin-wright/1a/12a/257",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Matt Rogers",
            discipline :            "Open Publishing Lab",
            "last-name" :           "Wright",
            date :                  "2011-02",
            relationship :          "Developer & Designer",
            "relationship-detail" : "Matt Straddled the line between designer and developer, and provided great perspective to the design team when it came to implementation",
            url :                   "matthewdrogers.com",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Josef Patoprsty",
            discipline :            "Open Publishing Lab",
            "last-name" :           "Patoprsty",
            date :                  "2011-02",
            relationship :          "Drupal Developer",
            "relationship-detail" : "Seppie, as he is affectionately known around the OPL, is a rock-solid PHP/Drupal Developer. Serious Heavy-lifter.",
            url :                   "http://imaginerit.ytmnd.com",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Guy Paddock",
            discipline :            "Open Publishing Lab",
            "last-name" :           "Paddock",
            date :                  "2011-03",
            relationship :          "Drupal Developer",
            "relationship-detail" : "Guy worked on the original Inews/MyNews Platforms. His familiarity with the code and the event truly helped during crunch-time",
            url :                   "https://twitter.com/#!/guypaddock",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Nathaniel Case",
            discipline :            "FOSS@RIT",
            "last-name" :           "Case",
            date :                  "2011-03",
            relationship :          "Developer",
            "relationship-detail" : "Nate is an all-aroud Hacker. Front-end or back-end, he picked up serious slack and filled in where needed.",
            url :                   "http://linkybook.rh.rit.edu",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Contributor",
            label :                 "Alex Gentile",
            discipline :            "Open Publishing Lab",
            "last-name" :           "Gentile",
            date :                  "2011-03",
            relationship :          "Developer",
            "relationship-detail" : "Alex did some stuff. Here is a description and some kind words.",
            url :                   "http://linkybook.rh.rit.edu",
            imageURL :              "http://nobelprize.org/nobel_prizes/chemistry/laureates/1990/corey_thumb.jpg"
        },
        {   type :                  "Event",
            label :                 "Post-Miami Meeting",
            discipline :            "Advisory Meeting",
            date :                  "2010-07-21",
            relationship :          "Event",
            "relationship-detail" : "Sitdown between PI's and Advisors after President Destler met with Alberto",
            url :                   "knightmeeting072110.txt"
        },
        {   type :                  "Event",
            label :                 "Mothership Brainstorm",
            discipline :            "Advisory Meeting",
            date :                  "2010-09-03",
            relationship :          "Event",
            "relationship-detail" : "21 Faculty from 17 Departments present their most mature and enticing projects as candidates for inclusion in the campaign",
            url :                   "knightmeeting090310.txt"
        },
        {   type :                  "Team Meeting",
            label :                 "Post-Mothership Strategy Meeting",
            discipline :            "Advisory Meeting",
            date :                  "2010-09-22",
            relationship :          "Event",
            "relationship-detail" : "It is decided. The OPL Inews/MyNews project is in, and here's what our next steps with Knight will be",
            url :                   "knightmeeting092210.txt"
        },
        {   type :                  "Event",
            label :                 "Gamification Meeting",
            discipline :            "Advisory Meeting",
            date :                  "2010-11-11",
            relationship :          "Event",
            "relationship-detail" : "Brainstormed Gamification/Social Gaming Angles for Project",
            url :                   "knightappsjmeeting111110.txt"
        },
        {   type :                  "Event",
            label :                 "Talent Meeting",
            discipline :            "Advisory Meeting",
            date :                  "2010-11-15",
            relationship :          "Event",
            "relationship-detail" : "Talent inventory and acquisition discussion. Candidates Identified and recruited",
            url :                   "knightsitdown111510.txt"
        },
        {   type :                  "Event",
            label :                 "Scoping Meeting",
            discipline :            "Advisory Meeting",
            date :                  "2010-12-10",
            relationship :          "Team Meeting",
            "relationship-detail" : "Talked through broad-view and scope of project, and starting the dev team",
            url :                   "knightfriday121010.txt"
        },
        {   type :                  "Team Meeting",
            label :                 "Winter Hackathon Demo",
            discipline :            "Team Meeting",
            date :                  "2011-01-28",
            relationship :          "Team Meeting",
            "relationship-detail" : "First Live Demo of Researched Components",
            url :                   "knightmeeting012811.txt"
        },
        {   type :                  "Team Meeting",
            label :                 "Pre-Winter Break Meeting",
            discipline :            "Team Meeting",
            date :                  "2010-12-17",
            relationship :          "Team Meeting",
            "relationship-detail" : "The OPL Inews/MyNews project is Demo'd. Evolution of platform is explained. Features are brainstormed. Design Concepts Discussed",
            url :                   "knightmeeting121710.txt"
        },
        {   type :                  "Team Meeting",
            label :                 "Priorities Meeting",
            discipline :            "Team Meeting",
            date :                  "2011-04-01",
            relationship :          "Team Meeting",
            "relationship-detail" : "Meetings get shorter. Priorities are discussed. Advisors get out of the way",
            url :                   "rise040111.txt"
        },
        {   type :                  "Team Meeting",
            label :                 "Miamoto's Pyramid, & Feature Breakdown",
            discipline :            "Team Meeting",
            date :                  "2011-01-07",
            relationship :          "Team Meeting",
            "relationship-detail" : "The Campaign is defined. Features are prioritized into 'must have', 'would be nice', and 'maybe later'",
            url :                   "riseabovethecrowdmeeting010711.txt"
        },
        {   type :                  "Team Meeting",
            label :                 "What we have, What's been built, What can we use?",
            discipline :            "Team Meeting",
            date :                  "2011-01-21",
            relationship :          "Team Meeting",
            "relationship-detail" : "Dev demo: Opensource projects that could provide functionality for 'must have' features",
            url :                   "riseabovethecrowdmeeting012111.txt"
        },
        {   type :                  "Team Meeting",
            label :                 "Design Time",
            discipline :            "Team Meeting",
            date :                  "2011-02-18",
            relationship :          "Team Meeting",
            "relationship-detail" : "Dev Team acknowledges it's time for designers. Hiring challenges in red-tape navigation emerge",
            url :                   "riseabovethecrowdmeeting021811.txt"
        },
        {   type :                  "Design Meeting",
            label :                 "Mobile App",
            discipline :            "Design Meeting",
            date :                  "2011-04-04",
            relationship :          "Design Meeting",
            "relationship-detail" : "Mobile app is central theme of meeting. Mockups are made for other HD/Big screen views",
            url :                   ""
        },
        {   type :                  "Design Meeting",
            label :                 "Typography, Terminology, and Mockups",
            discipline :            "Design Meeting",
            date :                  "2011-04-11",
            relationship :          "Design Meeting",
            "relationship-detail" : "Reports from Typography and Terminology Teams. Mockups are Critiqued for HD/Big screen views",
            url :                   ""
        },
        {   type :                  "Team Meeting",
            label :                 "Mobile Design Critique Meeting",
            discipline :            "Team Meeting",
            date :                  "2011-04-08",
            relationship :          "Team Meeting",
            "relationship-detail" : "Mobile app mockups are demo'd. Design team gets input for HD/Big Screen Interfaces",
            url :                   ""
        },
        {   type :                  "Team Meeting",
            label :                 "Final Regular Team Meeting",
            discipline :            "Team Meeting",
            date :                  "2011-04-29",
            relationship :          "Team Meeting",
            "relationship-detail" : "Shortest yet. T-shirt and Button Designs were printed and shown. Simile Exhibit Widget is Demo'd",
            url :                   ""
        },
        {   type :                  "Test Event",
            label :                 "Test Event #1",
            discipline :            "Test Event",
            date :                  "2011-04-08",
            relationship :          "Test Event",
            "relationship-detail" : "First Test Event for our Platform - RIT Breezeway Battle of The Bands",
            url :                   "http://events.rit.edu/event_detail.cfm?event_key=417920"
        },
        {   type :                  "Test Event",
            label :                 "Test Event #2",
            discipline :            "Test Event",
            date :                  "2011-04-29",
            relationship :          "Event",
            "relationship-detail" : "Second Test Event for our Platform - RIT Spring Fest",
            url :                   "http://www.rit.edu/studentaffairs/cab/springfestival"
        },
    ]
}
