{
    "types" : {
        "Contributor" : {
            pluralLabel: "Contributors",
        "Team Meeting" : {
            pluralLabel: "Team Meetings",
        "Dev Meeting" : {
            pluralLabel: "Dev Meetings",
        "Design Meeting" : {
            pluralLabel: "Design Meetings",
        "Test Event" : {
            pluralLabel: "Test Events",
        "Event" : {
            pluralLabel: "Events",
        "Hackathon" : {
            pluralLabel: "Hackathons"
        }
        }
        }
        }
        }
        }
        }
    },
    "properties": {
        "person" : {
            "valueType" : "item"
        }
    },
    "items" : [
        {   "type" :                  "Contributor",
            "label" :                 "Michael Riordan",
            "department" :            "Print Media",
            "discipline" :            "Publishing",
            "last-name" :             "Riordan",
            "date" :                  "2010-06",
            "role" :                  "Director",
            "relationship-detail" :   "Mentor and Product Owner",
            "url" :                   "http://opl.rit.edu",
            "person" :                "Michael Riordan",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Matthew Bernius",
            "department" :            "Multi-Disciplinary Studies",
            "discipline" :            "Publishing",
            "last-name" :             "Bernius",
            "date" :                  "2010-06",
            "role" :                  "Mentor",
            "relationship-detail" :   "Developer and Future Mentor",
            "url" :                   "http://www.mattbernius.com",
            "person" :                "Matthew Bernius",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "John Karahalis",
            "department" :            "Computing & Information Sciences",
            "discipline" :            "Lead Developer",
            "last-name" :             "Karahalis",
            "date" :                  "2010-06",
            "role" :                  "Lead Developer & Scrum Master",
            "major" :                 "Computer Science",
            "relationship-detail" :   "Theming, Modules, Site",
            "url" :                   "http://opl.rit.edu/researchers/current-students/john-karahalis/",
            "person" :                "John Karahalis",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Mark Newell",
            "department" :            "Open Publishing Lab",
            "discipline" :            "Developer",
            "shared" :                "no",
            "last-name" :             "Newell",
            "date" :                  "2010-06",
            "role" :                  "Drupal Developer",
            "relationship-detail" :   "Theming and Development, Co-op with Rochester Democrat & Chronicle",
            "url" :                   "http://www.markofthenewells.com",
            "person" :                "Mark Newell",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Remy DeCausemaker",
            "department" :            "Lab for Technological Literacy",
            "discipline" :            "Hactivist & Storyteller",
            "last-name" :             "DeCausemaker",
            "date" :                  "2010-06",
            "role" :                  "Storyteller",
            "relationship-detail" :   "Facilitation of Meetings and Development. Touchstone for each discipline, for each team",
            "url" :                   "http://foss.rit.edu/blog/decause",
            "person" :                "Remy DeCausemaker",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Stephen Jacobs",
            "department" :            "Lab for Technological Literacy",
            "discipline" :            "Interactive Games & Media",
            "last-name" :             "Jacobs",
            "date" :                  "2010-06",
            "role" :                  "Mentor",
            "relationship-detail" :   "Faculty Advisor of FOSS@RIT, Professor of Interactive Games & Media",
            "url" :                   "http://gryphonscratches.blogspot.com",
            "person" :                "Stephen Jacobs",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Vic Perotti",
            "department" :            "Business",
            "discipline" :            "Digital Entrepreneurship",
            "last-name" :             "Perotti",
            "date" :                  "2010-06",
            "role" :                  "Mentor",
            "relationship-detail" :   "Professor RIT College of Business, Champion of Digital Business",
            "url" :                   "http://www.perotti.com",
            "person" :                "Vic Perotti",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Andrea Hickerson",
            "department" :            "Communication",
            "discipline" :            "Journalism",
            "last-name" :             "Hickerson",
            "date" :                  "2010-06",
            "role" :                  "Mentor",
            "relationship-detail" :   "Professor RIT Department of Communication",
            "url" :                   "http://andreahickerson.blogspot.com",
            "person" :                "Andrea Hickerson",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Jaclyn Donner",
            "department" :            "Imaging Arts & Sciences",
            "discipline" :            "Graphic Design",
            "last-name" :             "Donner",
            "date" :                  "2010-11",
            "role" :                  "Designer",
            "major" :                 "Graphic Design",
            "relationship-detail" :   "Jackie Designed everything from our Logos, to our icons and T-Shirts. She is a rockstar",
            "url" :                   "http://jackiedonner.tumblr.com",
            "person" :                "Jaclyn Donner",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Mark DeMayo",
            "department" :            "FOSS@RIT",
            "discipline" :            "Developer/Designer",
            "last-name" :             "DeMayo",
            "date" :                  "2010-11",
            "role" :                  "Developer/Designer",
            "major" :                 "Game Design",
            "relationship-detail" :   "As one of our few front-end developers with Drupal experience, Mark was really the lynchpin between the design and dev team.",
            "url" :                   "http://people.rit.edu/~mxd6823",
            "person" :                "Mark DeMayo",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Ariel Zamparini",
            "department" :            "FOSS@RIT",
            "discipline" :            "Developer",
            "last-name" :             "Zamparini",
            "date" :                  "2010-11",
            "role" :                  "Drupal Developer",
            "major" :                 "Game Design",
            "relationship-detail" :   "Working primarily in the back-end and module research, Ariel provided his Drupal expertise when he could",
            "url" :                   "http://arielzamparini.com",
            "person" :                "Ariel Zamparini",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Ben Vanderberg",
            "department" :            "Imaging Arts & Sciences",
            "discipline" :            "Interaction Design",
            "last-name" :             "Vanderberg",
            "date" :                  "2011-03",
            "role" :                  "Designer",
            "major" :                 "New Media Publishing",
            "relationship-detail" :   "Ben's firm grasp of UI, web design, and Graffle was a boon to the Design team. He really shined as a Project Leader.",
            "url" :                   "http://www.benvanderberg.com",
            "person" :                "Ben Vanderberg",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Dustin Wright",
            "department" :            "Imaging Arts & Sciences",
            "discipline" :            "Graphic Design",
            "last-name" :             "Wright",
            "date" :                  "2011-03",
            "major" :                 "New Media Publishing",
            "role" :                  "Designer",
            "relationship-detail" :   "Dustin coordinated typography with Jackie, and produced many a mockup",
            "url" :                   "http://www.linkedin.com/pub/dustin-wright/1a/12a/257",
            "person" :                "Dustin Wright",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Matt Rogers",
            "department" :            "Computing & Information Sciences",
            "discipline" :            "Developer/Designer",
            "last-name" :             "Rogers",
            "date" :                  "2011-02",
            "role" :                  "Developer/Designer",
            "major" :                 "Computer Science",
            "relationship-detail" :   "Matt Straddled the line between designer and developer, and provided great perspective to the design team when it came to implementation",
            "url" :                   "http://matthewdrogers.com",
            "person" :                "Matt Rogers",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Josef Patoprsty",
            "department" :            "Computing & Information Sciences",
            "discipline" :            "Developer",
            "last-name" :             "Patoprsty",
            "date" :                  "2011-02",
            "role" :                  "Drupal Developer",
            "Major" :                 "Computer Science",
            "relationship-detail" :   "Seppie, as he is affectionately known around the OPL, is a rock-solid PHP/Drupal Developer. Serious Heavy-lifter.",
            "url" :                   "http://imaginerit.ytmnd.com",
            "person" :                "Josef Patoprsty",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Guy Paddock",
            "department" :            "Consultant - Red Bottle",
            "discipline" :            "Developer",
            "last-name" :             "Paddock",
            "date" :                  "2011-03",
            "role" :                  "Drupal Developer",
            "relationship-detail" :   "Guy worked on the original Inews/MyNews Platforms. His familiarity with the code and the event truly helped during crunch-time",
            "url" :                   "https://twitter.com/#!/guypaddock",
            "person" :                "Guy Paddock",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Nathaniel Case",
            "department" :            "FOSS@RIT",
            "discipline" :            "Developer/Designer",
            "last-name" :             "Case",
            "date" :                  "2011-03",
            "role" :                  "Developer/Designer",
            "major" :                 "Computer Science",
            "relationship-detail" :   "Nate is an all-aroud Hacker. Front-end or back-end, he picked up serious slack and filled in where needed.",
            "url" :                   "http://whynotwingnut.blogspot.com",
            "person" :                "Nate Case",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Contributor",
            "label" :                 "Alex Gentile",
            "department" :            "Consultant - Red Bottle",
            "discipline" :            "Developer",
            "last-name" :             "Gentile",
            "date" :                  "2011-03",
            "role" :                  "Drupal Developer",
            "relationship-detail" :   "Alex did some stuff. Here is a description and some kind words.",
            "url" :                   "https://twitter.com/#!/AlexGentile",
            "person" :                "Alex Gentile",
            "imageURL" :              "person.png",
        },
        {   "type" :                  "Hackathon",
            "label" :                 "NightShift Hackathon II",
            "discipline" :            "Hackathon",
            "date" :                  "2011-05-03",
            relationship :            "Hackathon",
            "relationship-detail" :   "Focused night-time coding session",
            "imageURL" :              "hackfest.png",
            "url" :                   ""
        },
        {   "type" :                  "Hackathon",
            "label" :                 "NightShift Hackathon I",
            "discipline" :            "Hackathon",
            "date" :                  "2011-05-02",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Focused night-time coding session",
            "imageURL" :              "hackfest.png",
            url :                     ""
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Sprint 6 Hackathon II",
            "discipline" :            "Hackathon",
            "date" :                  "2011-04-29",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Focused coding session centered on Mobile App Theming ",
            "imageURL" :              "hackfest.png",
            "url" :                   ""
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Sprint 6 Hackathon I",
            "discipline" :            "Hackathon",
            "date" :                  "2011-04-27",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Focused coding session centered on Mobile App Development",
            "imageURL" :              "hackfest.png",
            "url" :                   ""
        },
        {   "type" :                  "Hackathon",
            "label" :                 "BarcampROC Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2011-04-15",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Open coding session for BarcampROC presenters",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://barcamproc.org"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Sprint 4 Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2011-04-14",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Closed coding session centered on Drupal front-end development",
            "imageURL" :              "hackfest.png",
            "url" :                   ""
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Winter Wrap-up Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2011-02-18",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "End of the quarter coding session for FOSS@RIT university, client, and student projects",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/WWH"
        },
        {   "type" :                  "Hackathon",
            "label" :                 "Winter Hackathon",
            "discipline" :            "Hackathon",
            "date" :                  "2011-01-21",
            "relationship" :          "Hackathon",
            "relationship-detail" :   "Focused coding session centered on twitter and social media features",
            "imageURL" :              "hackfest.png",
            "url" :                   "http://foss.rit.edu/event/2011/01/21/day"
        },
        {   "type" :                  "Event",
            "label" :                 "Post-Miami Meeting",
            "discipline" :            "Advisory Meeting",
            "date" :                  "2010-07-21",
            "relationship" :          "Event",
            "relationship-detail" :   "Sitdown between PI's and Advisors after President Destler met with Alberto",
            "imageURL" :              "thoughts.png",
            "url" :                   "knightmeeting072110.txt"
        },
        {   "type" :                  "Event",
            "label" :                 "Mothership Brainstorm",
            "discipline" :            "Advisory Meeting",
            "date" :                  "2010-09-03",
            "relationship" :          "Event",
            "relationship-detail" :   "21 Faculty from 17 Departments present their most mature and enticing projects as candidates for inclusion in the campaign",
            "imageURL" :              "thoughts.png",
            "url" :                   "knightmeeting090310.txt"
        },
        {   "type" :                  "Event",
            "label" :                 "Post-Mothership Strategy Meeting",
            "discipline" :            "Advisory Meeting",
            "date" :                  "2010-09-22",
            "relationship" :          "Event",
            "relationship-detail" :   "It is decided. The OPL Inews/MyNews project is in, and here's what our next steps with Knight will be",
            "imageURL" :              "thoughts.png",
            "url" :                   "knightmeeting092210.txt"
        },
        {   "type" :                  "Event",
            "label" :                 "Gamification Meeting",
            "discipline" :            "Advisory Meeting",
            "date" :                  "2010-11-11",
            "relationship" :          "Event",
            "relationship-detail" :   "Brainstormed Gamification/Social Gaming Angles for Project",
            "imageURL" :              "thoughts.png",
            "url" :                   "knightappsjmeeting111110.txt"
        },
        {   "type" :                  "Event",
            "label" :                 "Talent Meeting",
            "discipline" :            "Advisory Meeting",
            "date" :                  "2010-11-15",
            "relationship" :          "Event",
            "relationship-detail" :   "Talent inventory and acquisition discussion. Candidates Identified and recruited",
            "imageURL" :              "thoughts.png",
            "url" :                   "knightsitdown111510.txt"
        },
        {   "type" :                  "Event",
            "label" :                 "Scoping Meeting",
            "discipline" :            "Advisory Meeting",
            "date" :                  "2010-12-10",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "Talked through broad-view and scope of project, and starting the dev team",
            "imageURL" :              "thoughts.png",
            "url" :                   "knightfriday121010.txt"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Winter Hackathon Demo",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-01-28",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "First Live Demo of Researched Components",
            "imageURL" :              "meeting.png",
            "url" :                   "knightmeeting012811.txt"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Pre-Winter Break Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2010-12-17",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "The OPL Inews/MyNews project is Demo'd. Evolution of platform is explained. Features are brainstormed. Design Concepts Discussed",
            "imageURL" :              "meeting.png",
            "url" :                   "knightmeeting121710.txt"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Priorities Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-04-01",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "Meetings get shorter. Priorities are discussed. Advisors get out of the way",
            "imageURL" :              "meeting.png",
            "url" :                   "rise040111.txt"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Miamoto's Pyramid & Feature Breakdown",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-01-07",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "The Campaign is defined. Features are prioritized into 'must have', 'would be nice', and 'maybe later'",
            "imageURL" :              "meeting.png",
            "url" :                   "riseabovethecrowdmeeting010711.txt"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "What we have, What's been built, What can we use?",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-01-21",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "Dev demo: Opensource projects that could provide functionality for 'must have' features",
            "imageURL" :              "meeting.png",
            "url" :                   "riseabovethecrowdmeeting012111.txt"
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Design Time",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-02-18",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "Dev Team acknowledges it's time for designers. Hiring challenges in red-tape navigation emerge",
            "imageURL" :              "meeting.png",
            "url" :                   "riseabovethecrowdmeeting021811.txt"
        },
        {   "type" :                  "Design Meeting",
            "label" :                 "Introduction, delegation, and roles",
            "discipline" :            "Design Meeting",
            "date" :                  "2011-04-04",
            "relationship" :          "Design Meeting",
            "relationship-detail" :   "Established schedule for quarter, and design team framework",
            "imageURL" :              "design.png",
            "url" :                   "risedesign040411.html"
        },
        {   "type" :                  "Design Meeting",
            "label" :                 "Design Basis & Brand Identity",
            "discipline" :            "Design Meeting",
            "date" :                  "2011-04-08",
            "relationship" :          "Design Meeting",
            "relationship-detail" :   "Decided base mockup that all other designs would inherit from",
            "imageURL" :              "design.png",
            "url" :                   "risedesign040811.html"
        },
        {   "type" :                  "Design Meeting",
            "label" :                 "Typography & Terminology",
            "discipline" :            "Design Meeting",
            "date" :                  "2011-04-11",
            "relationship" :          "Design Meeting",
            "relationship-detail" :   "Reports from Typography and Terminology Teams",
            "imageURL" :              "design.png",
            "url" :                   ""
        },
        {   "type" :                  "Design Meeting",
            "label" :                 "Big Screen/HD Mockups",
            "discipline" :            "Design Meeting",
            "date" :                  "2011-04-15",
            "relationship" :          "Design Meeting",
            "relationship-detail" :   "Mockups are Critiqued for HD/Big screen views",
            "imageURL" :              "design.png",
            "url" :                   ""
        },
        {   "type" :                  "Design Meeting",
            "label" :                 "Big Screen Demos",
            "discipline" :            "Design Meeting",
            "date" :                  "2011-04-18",
            "relationship" :          "Design Meeting",
            "relationship-detail" :   "Jumbotron Big screen views are demo'd",
            "imageURL" :              "design.png",
            "url" :                   ""
        },
        {   "type" :                  "Design Meeting",
            "label" :                 "HD Screen Demos",
            "discipline" :            "Design Meeting",
            "date" :                  "2011-04-23",
            "relationship" :          "Design Meeting",
            "relationship-detail" :   "Samsung HD screen views are demo'd",
            "imageURL" :              "design.png",
            "url" :                   ""
        },
        {   "type" :                  "Design Meeting",
            "label" :                 "Minding the Gaps",
            "discipline" :            "Design Meeting",
            "date" :                  "2011-04-25",
            "relationship" :          "Design Meeting",
            "relationship-detail" :   "Final 2 weeks of design/development are laid out, gaps identified",
            "imageURL" :              "design.png",
            "url" :                   ""
        },
        {   "type" :                  "Design Meeting",
            "label" :                 "Filling the Gaps",
            "discipline" :            "Design Meeting",
            "date" :                  "2011-04-29",
            "relationship" :          "Design Meeting",
            "relationship-detail" :   "Final Meeting pre-release freeze. Test Event platform deployed",
            "imageURL" :              "design.png",
            "url" :                   ""
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 1 Planning Meeting",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-03-08",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "Sprint 1 Week 1 planning meeting",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 1 Planning Meeting 2",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-03-15",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "Sprint 1 Week 2 Planning Meeting",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Event",
            "label" :                 "Documentation Release",
            "discipline" :            "Developer",
            "date" :                  "2011-03-16",
            "relationship" :          "Event",
            "relationship-detail" :   "'How to work with Rise source code' documentation released",
            "imageURL" :              "wrench.png",
            "url" :                   "risedocs031611.html"
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 2 Planning Meeting 1",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-03-21",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 2 Planning Meeting 2",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-03-28",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 2 Retrospective",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-04-01",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "Sprints 1 & 2 analyzed, and development is adjusted accordingly",
            "imageURL" :              "wrench.png",
            "url" :                   "risesprint2-040111.html"
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 3 Planning Meeting",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-04-05",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 4 Planning Meeting",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-04-11",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 5 Planning Meeting",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-04-18",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 5 Retrospective",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-04-22",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "Sprints 3-5 are analyzed, and development is adjusted accordingly",
            "imageURL" :              "wrench.png",
            "url" :                   "risesprint5-042211.html"
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Sprint 6 Planning Meeting",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-04-25",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Dev Meeting",
            "label" :                 "Final Dev Meeting, Pre-testing",
            "discipline" :            "Dev Meeting",
            "date" :                  "2011-05-02",
            "relationship" :          "Dev Meeting",
            "relationship-detail" :   "",
            "imageURL" :              "wrench.png",
            "url" :                   ""
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Mobile Design Critique Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-04-08",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "Mobile app mockups are demo'd. Design team gets input for HD/Big Screen Interfaces",
            "imageURL" :              "meeting.png",
            "url" :                   ""
        },
        {   "type" :                  "Team Meeting",
            "label" :                 "Final Regular Team Meeting",
            "discipline" :            "Team Meeting",
            "date" :                  "2011-04-29",
            "relationship" :          "Team Meeting",
            "relationship-detail" :   "Shortest yet. T-shirt and Button Designs were printed and shown. Simile Exhibit Widget is Demo'd",
            "imageURL" :              "meeting.png",
            "url" :                   ""
        },
        {   "type" :                  "Test Event",
            "label" :                 "Battle of the Bands Test Event",
            "discipline" :            "Test Event",
            "date" :                  "2011-04-08",
            "relationship" :          "Test Event",
            "relationship-detail" :   "First Test Event for our Platform - RIT Breezeway Battle of The Bands",
            "imageURL" :              "test.png",
            "url" :                   "http://events.rit.edu/event_detail.cfm?event_key=417920"
        },
        {   "type" :                  "Test Event",
            "label" :                 "RIT Spring Fest Test Event",
            "discipline" :            "Test Event",
            "date" :                  "2011-04-29",
            "relationship" :          "Event",
            "relationship-detail" :   "Second Test Event for our Platform - RIT Spring Fest",
            "imageURL" :              "test.png",
            "url" :                   "http://www.rit.edu/studentaffairs/cab/springfestival"
        },
    ]
}
